services:
  - type: web
    name: qr-backend
    env: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
    region: oregon
    rootDir: backend
